spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: jdbc:mysql://db:3306/staging_db?useSSL=false&serverTimezone=UTC
    username: staging_user
    password: staging_pass
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    properties:
      jakarta.persistence.jdbc.url: jdbc:mysql://localhost:3307/develop_db?useSSL=false&serverTimezone=UTC
      jakarta.persistence.jdbc.user: develop_user
      jakarta.persistence.jdbc.password: develop_pass
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082
