version: '3.8'

services:
  backend:
    build:
      context: ../../backend-api
    container_name: backend-develop
    environment:
      - SPRING_PROFILES_ACTIVE=develop
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=develop_db
      - DB_USERNAME=develop_user
      - DB_PASSWORD=develop_pass
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.1
    container_name: db-develop
    environment:
      MYSQL_DATABASE: develop_db
      MYSQL_USER: develop_user
      MYSQL_PASSWORD: develop_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db-develop-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "develop_user", "-pdevelop_pass"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 10s

volumes:
  db-develop-data:
